"""empty message

Revision ID: 55367c762063
Revises: 960361f5946f
Create Date: 2024-09-17 08:10:31.668536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55367c762063'
down_revision: Union[str, None] = '960361f5946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('notes', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tag', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('notes', 'tags')
    # ### end Alembic commands ###
